---
title: "Getting Population Data by Year"
author: "Melanie McCord"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fpp3)
library(tidycensus)
```

```{r}
api_key = Sys.getenv("US_CENSUS_API_KEY")
tidycensus::census_api_key(api_key)
vt <- get_acs(geography = "county", 
              variables = c(population = "B01001A_001"), 
              state = "IL", survey = "acs1",
              year = 2005) %>%
  filter(county == "Cook County")

vt
```

```{r}
load_variables(2019, dataset = "acs1")
```

```{r}
years <- lst(2012, 2019) 

# which counties?
my_counties <- c(
  "Alameda",
  "Contra Costa",
  "Marin",
  "Napa",
  "San Francisco",
  "San Mateo",
  "Santa Clara",
  "Solano",
  "Sonoma"
  )

# which census variables?
my_vars <- c(
  total_pop = "B01003_001",
  median_income = "B19013_001"
  )

# loop over list of years and get 1 year acs estimates
bay_area_multi_year <- map_dfr(
  years,
  ~ get_acs(
      geography = "county",
      variables = my_vars,
      state = "CA",
      county = my_counties,
      year = .x,
      survey = "acs1",
      geometry = FALSE
      ),
  .id = "year"  # when combining results, add id var (name of list item)
  ) %>%
  select(-moe) %>%  # shhhh
  arrange(variable, NAME)
```

```{r}
head(bay_area_multi_year)
```

```{r}
for (i in 2012:2022) {
  my_vars <- c(
  total_pop = "B01003_001")
zipChicagoDf <- get_acs(geography = 'zcta', variables = c( total_pop = "B01003_001"),year = i, geometry = FALSE, survey="acs1") %>%
                  select(GEOID, NAME, variable, estimate) %>% 
                  filter(str_detect( GEOID,"^606")) %>%  ## add a str filter
                  spread(variable, estimate) %>%
  mutate(year = i)
print(zipChicagoDf)
}

```

```{r}
years <-2005:2019

# which counties?
my_counties <- c(
  "Chicago"
  )

# which census variables?
my_vars <- c(
  total_pop = "B01003_001",
  median_income = "B19013_001"
  )

# loop over list of years and get 1 year acs estimates
chicago <- map_dfr(
  years,
  ~ get_acs(geography = 'zcta', variables = c( total_pop = "B01003_001"),year = .x, geometry = FALSE, survey = "acs1") %>%
                  select(GEOID, NAME, variable, estimate) %>% 
                  filter(str_detect( GEOID,"^606")) %>%  ## add a str filter
                  spread(variable, estimate) %>% 
                  select(GEOID, total_pop) %>%
  summarize(Population = sum(total_pop)),
  .id = "year"  # when combining results, add id var (name of list item)
  ) %>%
  select(-moe) %>%  # shhhh
  arrange(variable, NAME)
```


```{r}
write_csv(cook_county_multiyears, "data/cook_county_estimates_2005-2019.csv")
```
